models:
  image: zanebilous/django
  external_links:
    - mysql:db
  volumes:
    - ./models:/app
  ports:
    - "8001:8000"
  command: bash -c "python manage.py migrate && python manage.py loaddata && mod_wsgi-express start-server --working-directory . --reload-on-changes ./models/wsgi.py"

exp:
  image: zanebilous/django
  container_name: exp
  links:
    - models:models-api
    - kafka:kafka
    - es:es
  ports:
    - "8002:8000"
  volumes:
    - ./exp:/app
  command: "mod_wsgi-express start-server --reload-on-changes exp/wsgi.py"

web:
  image: zanebilous/django
  container_name: web-server
  links:
    - exp:exp-api

  volumes:
    - ./web:/app
  command: "mod_wsgi-express start-server --reload-on-changes ./web/wsgi.py --log-to-terminal"

web2:
  image: zanebilous/django
  container_name: web-server2
  links:
    - exp:exp-api

  volumes:
    - ./web:/app
  command: "mod_wsgi-express start-server --reload-on-changes ./web/wsgi.py --log-to-terminal"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   links:
      - kafka:kafka
      - es:es
   volumes:
      - ./batch:/app
    # <run a python script that pulls messages from Kafka and indexs that in ES>
   command: "python batch.py"

haproxy:
    # build: ./load_balancer
    image: haproxy:1.8
    container_name: haproxy
    links:
      - web:web-api
      - web2:web2-api
    ports:
      - "8000:8000"
    volumes:
      - ./load_balancer/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

selenium-chrome:
  shm_size: 1G
  image: selenium/standalone-chrome
  container_name: selenium-chrome
  links:
    - web:web
  ports:
    - "4444:4444"

selenium-test:
  shm_size: 1G
  image: zanebilous/django
  container_name: selenium-test
  links:
    - selenium-chrome:selenium-chrome
    - web:web
  volumes:
    - ./selenium:/app
  command: bash -c "pip install selenium==3.14.0 && sleep 7 && python selenium_test.py"

