models:
  image: zanebilous/django
  external_links:
    - mysql:db
  volumes:
    - .:/app
  ports:
    - "8001:8000"
  command: bash -c "python manage.py makemigrations && python manage.py migrate && mod_wsgi-express start-server --working-directory . --reload-on-changes ./swifey/wsgi.py"
