models:
  image: zanebilous/django
  external_links:
    - mysql:db
  volumes:
    - ./models:/app
  ports:
    - "8001:8000"
  command: bash -c "python manage.py migrate && mod_wsgi-express start-server --working-directory . --reload-on-changes ./models/wsgi.py"

exp:
  image: zanebilous/django
  container_name: exp
  links:
    - models:models-api
    - kafka:kafka
    - es:es
  ports:
    - "8002:8000"
  volumes:
    - ./exp:/app
  command: "mod_wsgi-express start-server --reload-on-changes exp/wsgi.py"

web:
  image: zanebilous/django
  container_name: web-server
  links:
    - exp:exp-api

  volumes:
    - ./web:/app
  command: "mod_wsgi-express start-server --reload-on-changes ./web/wsgi.py --log-to-terminal"

web2:
  image: zanebilous/django
  container_name: web-server2
  links:
    - exp:exp-api

  volumes:
    - ./web:/app
  command: "mod_wsgi-express start-server --reload-on-changes ./web/wsgi.py --log-to-terminal"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   links:
      - kafka:kafka
      - es:es
   volumes:
      - ./batch:/app
    # <run a python script that pulls messages from Kafka and indexs that in ES>
   command: "python batch.py"

haproxy:
    # build: ./load_balancer
    image: haproxy:1.8
    container_name: haproxy
    links:
      - web:web-api
      - web2:web2-api
    ports:
      - "8000:8000"
    volumes:
      - ./load_balancer/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

selenium-chrome:
  shm_size: 1G
  image: selenium/standalone-chrome
  container_name: selenium-chrome
  links:
    - web:web
  ports:
    - "4444:4444"

selenium-test:
  shm_size: 1G
  image: zanebilous/django
  container_name: selenium-test
  links:
    - selenium-chrome:selenium-chrome
    - web:web
  volumes:
    - ./selenium:/app
  command: bash -c "pip install selenium==3.14.0 && sleep 7 && python selenium_test.py"

spark-master:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
  container_name: spark-master
  hostname: spark-master
  environment:
    MASTER: spark://spark-master:7077
    SPARK_CONF_DIR: /conf
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./data:/tmp/data

spark-worker:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  container_name: spark-worker
  hostname: spark-worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 512m
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
  links:
    - spark-master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081:8081
  volumes:
    - ./data:/tmp/data
  #In the data directory, complete code to make it work 
  spark-batch:
   image: tp33/django
   container_name: spark-batch
   links:
      - kafka:kafka
   volumes:
      - ./data:/tmp/data
   command: bash -c "python /tmp/data/spark.py"