# Generated by Django 2.1 on 2018-10-30 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authenticator',
            fields=[
                ('user_id', models.IntegerField()),
                ('authenticator', models.IntegerField(primary_key=True, serialize=False)),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='created_by',
            new_name='used_id',
        ),
        migrations.AddField(
            model_name='user',
            name='authenticator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Authenticator'),
        ),
    ]
