# Generated by Django 2.1 on 2018-10-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(default='S', max_length=1),
            preserve_default=False,
        ),
    ]
