# Generated by Django 2.1 on 2018-10-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181030_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='authenticator',
        ),
        migrations.AlterField(
            model_name='authenticator',
            name='authenticator',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
