# Generated by Django 2.1 on 2018-10-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='for_swipes',
            field=models.BooleanField(default=True),
        ),
    ]
