# Generated by Django 2.1 on 2018-12-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181129_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('listing_id', models.IntegerField(primary_key=True, serialize=False)),
                ('recommended', models.ManyToManyField(to='app.Listing')),
            ],
        ),
    ]
