# Generated by Django 2.1 on 2018-12-17 17:55

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='recommended',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommended',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
