# Generated by Django 2.1 on 2018-11-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181104_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='listings',
            field=models.TextField(default=''),
        ),
    ]
