# Generated by Django 2.1 on 2018-11-12 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181104_1934'),
        ('app', '0004_auto_20181110_2121'),
    ]

    operations = [
    ]
