# Generated by Django 2.1 on 2018-11-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge_20181112_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='listings',
            field=models.TextField(default='[]'),
        ),
    ]
